# Generated by Django 3.0.3 on 2020-09-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_dadosform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosform',
            name='aniversario',
            field=models.CharField(max_length=264, unique=True),
        ),
    ]
