# Generated by Django 3.0.3 on 2020-09-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200920_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
    ]
