# Generated by Django 3.0.3 on 2020-09-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosForm',
        ),
    ]
