# Generated by Django 3.0.3 on 2020-09-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_dadosform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosform',
            old_name='endereço',
            new_name='endereco',
        ),
        migrations.AddField(
            model_name='dadosform',
            name='estado',
            field=models.CharField(default='brasil', max_length=264),
        ),
    ]
