# Generated by Django 3.0.3 on 2020-09-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200922_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosform',
            name='estado',
        ),
    ]
